# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: buildapplication
  displayName: "Build .Net Framework"
  jobs:
    - job: buildjob    
      steps:
      - task: NuGetToolInstaller@1
        displayName: "Installing nuget"

      - task: NuGetCommand@2
        displayName: "Restore Nuget Packages"
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        displayName: "MS Build Asp.Net"
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactStagingDirectory)'
          artifact: 'aspnet-package'
          publishLocation: 'pipeline'

- stage: deployaws
  dependsOn: buildapplication
  displayName: "Deploy to Aws App Service"
  jobs:
    - deployment: "awsdeployment"    
      strategy:
        runOnce:
          deploy:
           steps:
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Azure Bitworks'
                appType: 'webApp'
                WebAppName: 'demo-asp-net'
                packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
               
            

